# Chapter 2 Image classification

## Training MNIST model in Keras

### Preparing the dataset


In [2]:
import keras

/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [1]:
batch_size = 128 
no_classes = 10
epochs = 2
image_height, image_width = 28,28

In [34]:
## Loading the dataset
(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()

In [35]:
### Formatting the data to make each pixel and individual array adding that way
###  other dimension to the data
x_train = x_train.reshape(x_train.shape[0], image_height, image_width, 1)

x_test = x_test.reshape(x_test.shape[0], image_height, image_width, 1)
input_shape = (image_height, image_width, 1)

In [36]:
### Converting integers from 0 to 255 to float allowing division
x_train = x_train.astype('float32')
x_test = x_test.astype('float32')


In [37]:
### normalizing data to be from 0 to 1 to make it easier to train
x_train /= 255
x_test /= 255

In [41]:
#print(x_train[0][12])
print(y_test)

[[0. 0. 0. ... 1. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [40]:
### making one shoot encoding classes
y_train = keras.utils.to_categorical(y_train, no_classes)
y_test = keras.utils.to_categorical(y_test, no_classes)

In [42]:
def simple_cnn(input_shape):
    model = keras.models.Sequential()
    model.add(keras.layers.Conv2D(filters = 64,
                                  kernel_size= (3,3),
                                 activation= 'relu',
                                 input_shape = input_shape)
             )
    model.add(keras.layers.Conv2D(filters = 128,
                                 kernel_size= (3,3),
                                  activation = 'relu'
                                 )
             )
    model.add( keras.layers.MaxPooling2D(pool_size = (2,2) ) )
    model.add( keras.layers.Dropout(rate = 0.3))
    model.add( keras.layers.Flatten()) ##Make it one dimension
    model.add( keras.layers.Dense(units= 1024, activation= 'relu'))
    model.add( keras.layers.Dropout(rate= 0.3) )
    model.add( keras.layers.Dense(units= no_classes, activation='softmax'))
    model.compile(loss= keras.losses.categorical_crossentropy,
                  optimizer = keras.optimizers.Adam(),
                  metrics = ['accuracy']
                )
    return model

simple_cnn_model = simple_cnn(input_shape)
    

In [ ]:
simple_cnn_model.fit(x_train, y_train, batch_size, epochs, (x_test, y_test))

train_loss, train_accuracy  = simple_cnn_model.evaluate(x_train, y_train,
                                                        verbose= 0)
print("Train data loss:" , train_loss)
print("train data accuracy:", train_accuracy)

Epoch 1/2
Epoch 2/2


In [ ]:
test_loss, test_accuracy = simple_cnn_model.evaluate(x_test, y_test, verbose= 0)

print("Test data loss:" , test_loss)
print("Test data accuracy:", test_accuracy)